//For use with various spawners! Put your selections inside of a list!
/var/global/list/theme_farm = list(
			/mob/living/simple_mob/animal/goat,
			/mob/living/simple_mob/animal/passive/cow,
			/mob/living/simple_mob/vore/sheep,
			/mob/living/simple_mob/animal/passive/chicken,
			/mob/living/simple_mob/vore/horse,
			/mob/living/simple_mob/vore/horse/big,
			/mob/living/simple_mob/vore/alienanimals/teppi,
			/mob/living/simple_mob/vore/bee
		)
/var/global/list/theme_bird = list(
			/mob/living/simple_mob/animal/passive/bird = 1,
			/mob/living/simple_mob/animal/passive/bird/azure_tit = 1,
			/mob/living/simple_mob/animal/passive/bird/black_bird = 1,
			/mob/living/simple_mob/animal/passive/bird/european_robin = 1,
			/mob/living/simple_mob/animal/passive/bird/goldcrest = 1,
			/mob/living/simple_mob/animal/passive/bird/ringneck_dove = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/black_headed_caique = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/budgerigar = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/budgerigar/blue = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/budgerigar/bluegreen = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/cockatiel = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/cockatiel/grey = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/cockatiel/white = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/cockatiel/yellowish = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/eclectus = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/grey_parrot = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/kea = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/pink_cockatoo = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/sulphur_cockatoo = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/white_caique = 1,
			/mob/living/simple_mob/animal/passive/bird/parrot/white_cockatoo = 1,
			/mob/living/simple_mob/animal/space/goose = 4,
			/mob/living/simple_mob/animal/passive/penguin = 4,
			/mob/living/simple_mob/vore/seagull = 4
		)
/var/global/list/theme_forest = list(
			/mob/living/simple_mob/vore/wolf = 10,
			/mob/living/simple_mob/vore/wolf/direwolf = 5,
			/mob/living/simple_mob/vore/greatwolf = 1,
			/mob/living/simple_mob/vore/greatwolf/black = 1,
			/mob/living/simple_mob/vore/greatwolf/grey = 1,
			/mob/living/simple_mob/animal/passive/fox = 10,
			/mob/living/simple_mob/animal/passive/hare = 10,
			/mob/living/simple_mob/animal/passive/opossum = 10,
			/mob/living/simple_mob/vore/rabbit = 10,
			/mob/living/simple_mob/animal/space/bear = 5,
			/mob/living/simple_mob/animal/space/bear/brown = 5,
			/mob/living/simple_mob/vore/redpanda = 10,
			/mob/living/simple_mob/vore/redpanda/blue = 5,
			/mob/living/simple_mob/vore/redpanda/fae = 1,
			/mob/living/simple_mob/vore/fennec = 10,
			/mob/living/simple_mob/vore/fennec/huge = 1,
			/mob/living/simple_mob/animal/passive/fennec = 5,
			/mob/living/simple_mob/vore/fennix = 5,
			/mob/living/simple_mob/animal/passive/mouse/jerboa = 10,
			/mob/living/simple_mob/vore/alienanimals/dustjumper = 10,
			/mob/living/simple_mob/vore/deer = 10,
			/mob/living/simple_mob/vore/squirrel = 10
		)
/var/global/list/theme_jungle = list(
			/mob/living/simple_mob/vore/hippo = 10,
			/mob/living/simple_mob/vore/aggressive/frog = 10,
			/mob/living/simple_mob/vore/aggressive/panther = 10,
			/mob/living/simple_mob/vore/aggressive/rat = 10,
			/mob/living/simple_mob/animal/passive/mouse/rat = 10,
			/mob/living/simple_mob/vore/leopardmander = 10,
			/mob/living/simple_mob/vore/leopardmander/blue = 5,
			/mob/living/simple_mob/vore/leopardmander/exotic = 1,
			/mob/living/simple_mob/vore/weretiger = 5,
			/mob/living/simple_mob/animal/passive/pillbug = 10,
			/mob/living/simple_mob/animal/passive/tindalos = 10,
			/mob/living/simple_mob/animal/passive/yithian = 10,
			/mob/living/simple_mob/vore/pakkun = 5,
			/mob/living/simple_mob/vore/pakkun/fire = 5,
			/mob/living/simple_mob/vore/pakkun/purple = 5,
			/mob/living/simple_mob/vore/pakkun/sand = 5,
			/mob/living/simple_mob/vore/pakkun/snapdragon = 5
		)
/var/global/list/theme_domestic = list(
			/mob/living/simple_mob/animal/passive/cat = 10,
			/mob/living/simple_mob/animal/passive/cat/black = 10,
			/mob/living/simple_mob/animal/passive/cat/bread = 5,
			/mob/living/simple_mob/animal/passive/cat/cak = 5,
			/mob/living/simple_mob/animal/passive/cat/bluespace = 1,
			/mob/living/simple_mob/animal/passive/dog/brittany = 10,
			/mob/living/simple_mob/animal/passive/dog/corgi = 10,
			/mob/living/simple_mob/animal/passive/dog/tamaskan = 10,
			/mob/living/simple_mob/animal/passive/dog/void_puppy = 1,
			/mob/living/simple_mob/vore/woof = 5,
			/mob/living/simple_mob/vore/wolf/direwolf/dog = 5,
			/mob/living/simple_mob/vore/otie/feral = 5,
			/mob/living/simple_mob/vore/otie/feral/chubby = 5,
			/mob/living/simple_mob/vore/otie/red = 5,
			/mob/living/simple_mob/vore/otie/red/chubby = 5
		)
/var/global/list/theme_lizard = list(
			/mob/living/simple_mob/animal/passive/snake = 10,
			/mob/living/simple_mob/animal/passive/snake/red = 10,
			/mob/living/simple_mob/animal/passive/snake/python = 10,
			/mob/living/simple_mob/vore/aggressive/dino = 10,
			/mob/living/simple_mob/vore/aggressive/dragon = 10,
			/mob/living/simple_mob/vore/aggressive/dragon/virgo3b = 10,
			/mob/living/simple_mob/vore/aggressive/giant_snake = 10,
			/mob/living/simple_mob/vore/cryptdrake = 1,
			/mob/living/simple_mob/vore/raptor = 10
		)
/var/global/list/theme_sif = list(
			/mob/living/simple_mob/animal/sif/diyaab = 10,
			/mob/living/simple_mob/animal/sif/duck = 10,
			/mob/living/simple_mob/animal/sif/frostfly = 10,
			/mob/living/simple_mob/animal/sif/glitterfly = 10,
			/mob/living/simple_mob/animal/sif/glitterfly/rare = 1,
			/mob/living/simple_mob/animal/sif/sakimm = 10,
			/mob/living/simple_mob/animal/sif/sakimm/intelligent = 1,
			/mob/living/simple_mob/animal/sif/savik = 10,
			/mob/living/simple_mob/animal/sif/shantak = 10,
			/mob/living/simple_mob/animal/sif/shantak/leader = 1,
			/mob/living/simple_mob/animal/sif/siffet = 10,
			/mob/living/simple_mob/animal/sif/tymisian = 10,
			/mob/living/simple_mob/animal/sif/shantak/leader = 1,
			/mob/living/simple_mob/animal/sif/shantak = 10,
			/mob/living/simple_mob/animal/sif/savik = 10,
			/mob/living/simple_mob/animal/sif/hooligan_crab = 5,
			/mob/living/simple_mob/animal/sif/leech = 10
		)
/var/global/list/theme_space = list(
			/mob/living/simple_mob/animal/space/bats/cult/strong = 10,
			/mob/living/simple_mob/vore/bat = 10,
			/mob/living/simple_mob/animal/space/carp = 10,
			/mob/living/simple_mob/animal/space/carp/large = 5,
			/mob/living/simple_mob/animal/space/carp/large/huge/vorny = 1,
			/mob/living/simple_mob/vore/alienanimals/space_jellyfish = 10,
			/mob/living/simple_mob/vore/alienanimals/startreader = 5,
			/mob/living/simple_mob/vore/aggressive/corrupthound = 10,
			/mob/living/simple_mob/vore/aggressive/corrupthound/prettyboi = 1,
			/mob/living/simple_mob/animal/passive/fox/syndicate = 1,
			/mob/living/simple_mob/vore/aggressive/deathclaw = 10,
			/mob/living/simple_mob/vore/aggressive/mimic = 10,
			/mob/living/simple_mob/animal/space/tree = 5,
			/mob/living/simple_mob/vore/jelly = 10,
			/mob/living/simple_mob/vore/oregrub = 10,
			/mob/living/simple_mob/vore/oregrub/lava = 10,
			/mob/living/simple_mob/vore/solargrub = 5,
			/mob/living/simple_mob/vore/sect_drone = 10,
			/mob/living/simple_mob/vore/sect_queen = 1,
			/mob/living/simple_mob/creature/strong = 10,
			/mob/living/simple_mob/animal/space/gnat = 10,
			/mob/living/simple_mob/animal/space/ray = 10,
			/mob/living/simple_mob/animal/space/shark = 10,
			/mob/living/simple_mob/tomato = 10,
			/mob/living/simple_mob/vore/vore_hostile/abyss_lurker = 10,
			/mob/living/simple_mob/vore/vore_hostile/leaper = 10,
			/mob/living/simple_mob/vore/vore_hostile/gelatinous_cube = 10,
			/mob/living/simple_mob/vore/xeno_defanged = 10
		)
