// Modes for examine text output
#define EXAMINE_MODE_DEFAULT		 0
#define EXAMINE_MODE_INCLUDE_USAGE	 1
#define EXAMINE_MODE_SWITCH_TO_PANEL 2

// Should be one higher than the above
#define EXAMINE_MODE_MAX			 3

// Modes for parsing multilingual speech
#define MULTILINGUAL_DEFAULT			0
#define MULTILINGUAL_SPACE				1
#define MULTILINGUAL_DOUBLE_DELIMITER	2
#define MULTILINGUAL_OFF				3

#define MULTILINGUAL_MODE_MAX			4

// RS Add: Rate-limit character setup reloads and marking selection to prevent UI spam (Lira, November 2025)
#define CHARSETUP_RELOAD_DELAY_SECONDS 5
#define CHARSETUP_RELOAD_DELAY (CHARSETUP_RELOAD_DELAY_SECONDS SECONDS)
#define CHARSETUP_MARKING_DELAY_SECONDS 1
#define CHARSETUP_MARKING_DELAY (CHARSETUP_MARKING_DELAY_SECONDS SECONDS)

// RS Add: Sound preferences panel (Lira, June 2026)
#define SOUND_PANEL_GROUP_MUSIC "Music/Media"
#define SOUND_PANEL_GROUP_WORLD "World"
#define SOUND_PANEL_GROUP_ITEMS "Items"
#define SOUND_PANEL_GROUP_CHAT "Chat"
#define SOUND_PANEL_GROUP_VORE "Vore/Emotes"
#define SOUND_PANEL_GROUP_STAFF "Staff"
#define SOUND_PANEL_TOGGLE_ACTION_DELAY (0.5 SECONDS)
#define SOUND_PANEL_SLIDER_ACTION_DELAY (0.2 SECONDS)
#define SOUND_PANEL_SAVE_DELAY (60 SECONDS)

// RS Add: Preference settings panel (Lira, July 2026)
#define PREFERENCE_SETTINGS_GROUP_INTERFACE "Interface/HUD"
#define PREFERENCE_SETTINGS_GROUP_CHAT "Chat/Ghost"
#define PREFERENCE_SETTINGS_GROUP_RUNECHAT "Runechat"
#define PREFERENCE_SETTINGS_GROUP_GAMEPLAY "Gameplay/RP"
#define PREFERENCE_SETTINGS_GROUP_STAFF "Staff"
#define PREFERENCE_SETTINGS_TOGGLE_ACTION_DELAY (0.5 SECONDS)
#define PREFERENCE_SETTINGS_SAVE_DELAY (60 SECONDS)
